# Custom Language File for Launcher Customizer

[ejs.app]
title = "RexCraft Launcher - v1.0.0"

[ejs.landing]
mediaGitHubURL = "https://discord.rexcraft.it"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.rexcraft.it"

[ejs.settings]
sourceGithubLink = "https://discord.rexcraft.it"
supportLink = "https://discord.rexcraft.it"

[ejs.welcome]
welcomeHeader = "BENVENUTO/A"
welcomeDescription = ""
welcomeDescCTA = "Copyright © 2026 IMPEROMC STUDIOS"
